name: Release binaries

concurrency:
  group: release
  cancel-in-progress: true

on:
  push:
    tags:
      - "**"

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd src/cli
          make -j
          mv cli bbk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bbk
          path: src/cli/bbk

  release:
    name: Create GitHub Release
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup | Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/.

      - name: Setup | Generate release notes
        run: git log -1 --pretty='%s' > RELEASE.md

      - name: Build | Publish
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          body_path: RELEASE.md
